apiVersion: 1

deleteDatasources:
  - name: XCS Prometheus
    orgId: 1

datasources:
  - name: XCS Prometheus
    uid: xcs-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
