[package]
name = "substreams-xcs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.6"
prost = "0.13"
prost-types = "0.13"
sha2 = { version = "0.10", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
substreams-database-change = "2.1"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
